prompt  ...... incluindo registros padrões para F_SITCBSIBS
Rem ---------------------------------------------------------------------------
Rem  Anderson Gaitolini em April/2025
Rem  Geração de INSERTs para a tabela F_SITCBSIBS com base na query: SELECT * FROM F_SITCBSIBS

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '000', 'Tributação integral');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota zero');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota zero apenas CBS e reduzida em 60% para IBS');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota reduzida em 80%');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota reduzida em 60%');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota reduzida em 40%');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '200', 'Alíquota reduzida em 30%');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '400', 'Isenção');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '410', 'Imunidade e não incidência');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '510', 'Diferimento');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '550', 'Suspensão');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '620', 'Tributação monofásica');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '800', 'Transferência de crédito');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '810', 'Ajustes');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

BEGIN
  INSERT INTO F_SITCBSIBS (STX_CODIGO, STX_SITCST, STX_DSCCST)
  VALUES (SEQ_SITCBSIBS.NEXTVAL, '900', 'Outros');
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    NULL;
END;
/

SET DEFINE ON;
